# Generated by Django 2.2 on 2020-09-26 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200910_2045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
