# Generated by Django 2.2 on 2020-09-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200926_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Продукты питания', 'Продукты питания'), ('Хоз. товары', 'Хоз. товары'), ('Детские игрушки', 'Детские игрушки'), ('Бытовая Техника', 'Бытовая Техника')], default=None, max_length=20, verbose_name='Категория'),
        ),
    ]
